/* This file is autogenerated, do not edit*/
#include "moc_Tests.cpp"
#include "moc_MetaManager.cpp"
#include "moc_Recorder.cpp"
#include "moc_DualInstance.cpp"
#include "moc_DualPlayer.cpp"
#include "moc_EqualizerDialog.cpp"
#include "moc_MediaList.cpp"
#include "moc_Player.cpp"
