######################################################################
# Automatically generated by qmake (3.0) tir feb 23 09:38:08 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += . \..

# Input
HEADERS += ..\abstractcamera.h

SOURCES += cameratests.cpp \
            ..\abstractcamera.cpp
